# Generated by Django 5.2.4 on 2025-10-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(help_text='Name of the member who received the reminder', max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the reminder was sent')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', help_text='Whether the email was sent successfully', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error details if the send failed', null=True)),
                ('balance_shown', models.CharField(blank=True, help_text='The balance value shown in the reminder (for reference)', max_length=50)),
            ],
            options={
                'verbose_name': 'Reminder Log',
                'verbose_name_plural': 'Reminder Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
